"""Planner Agent interface definition for LangGraph."""

from abc import abstractmethod
from typing import List, Optional
from pydantic import BaseModel, Field

from app.agents.base import BaseAgentInterface, BaseAgentState


class PlanOutput(BaseModel):
    """Structured research plan generated by the Planner Agent."""

    research_goal: str = Field(description="Primary research objective")
    sub_queries: List[str] = Field(description="Decomposed sub-queries for search agents")
    target_domains: Optional[List[str]] = Field(default=None, description="Preferred domains to search")
    steps: List[str] = Field(description="Sequential execution steps")


class PlannerAgentInterface(BaseAgentInterface):
    """Abstract interface for the Planner Agent responsible for query decomposition and strategy."""

    @property
    def agent_name(self) -> str:
        return "PlannerAgent"

    @abstractmethod
    async def create_plan(self, query: str, depth: str = "standard") -> PlanOutput:
        """Decompose user research query into a structured research plan.

        Args:
            query: Raw user research prompt.
            depth: Research depth ('quick', 'standard', 'deep').

        Returns:
            PlanOutput schema containing sub-queries and execution steps.
        """
        pass

    @abstractmethod
    async def execute(self, state: BaseAgentState) -> BaseAgentState:
        """Execute planner node within the LangGraph workflow."""
        pass
