"""Report Agent interface definition for LangGraph."""

from abc import abstractmethod
from typing import Any, Dict, List
from pydantic import BaseModel, Field

from app.agents.base import BaseAgentInterface, BaseAgentState
from app.agents.citation import CitationItem
from app.agents.fact_checker import VerifiedFact
from app.agents.planner import PlanOutput


class FinalReportOutput(BaseModel):
    """Structured final report payload generated by ReportAgent."""

    title: str = Field(description="Report header title")
    summary: str = Field(description="Executive summary paragraph")
    content_markdown: str = Field(description="Full Markdown report body with in-text citations")
    key_findings: List[Dict[str, Any]] = Field(description="Structured key findings list")
    word_count: int = Field(ge=0, description="Total report word count")


class ReportAgentInterface(BaseAgentInterface):
    """Abstract interface for the Report Agent responsible for synthesizing final reports."""

    @property
    def agent_name(self) -> str:
        return "ReportAgent"

    @abstractmethod
    async def synthesize_report(
        self,
        query: str,
        plan: PlanOutput,
        facts: List[VerifiedFact],
        citations: List[CitationItem],
    ) -> FinalReportOutput:
        """Synthesize verified facts and citations into a comprehensive Markdown report.

        Args:
            query: Original user research prompt.
            plan: PlanOutput from PlannerAgent.
            facts: Verified facts from FactCheckerAgent.
            citations: Formatted citations from CitationAgent.

        Returns:
            FinalReportOutput containing summary, Markdown content, and key findings.
        """
        pass

    @abstractmethod
    async def execute(self, state: BaseAgentState) -> BaseAgentState:
        """Execute report node within the LangGraph workflow."""
        pass
