"""add missing columns

Revision ID: 501d0a946e1a
Revises: 2026_08_20_0003
Create Date: 2026-08-21 01:28:40.389725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '501d0a946e1a'
down_revision: Union[str, None] = '2026_08_20_0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply forward migration.

    This function is executed by ``alembic upgrade``.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_execution_logs', sa.Column('cost_usd', sa.Float(), nullable=True))
    op.alter_column('agent_execution_logs', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.add_column('payments', sa.Column('cost_usd', sa.Float(), nullable=True))
    op.add_column('payments', sa.Column('retry_count', sa.Integer(), nullable=False))
    op.add_column('payments', sa.Column('error_message', sa.Text(), nullable=True))
    op.alter_column('payments', 'currency',
               existing_type=sa.VARCHAR(length=3),
               server_default=None,
               existing_nullable=False)
    op.alter_column('payments', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('payments', 'credits_awarded',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.add_column('research_jobs', sa.Column('current_agent', sa.String(length=100), nullable=True))
    op.add_column('research_jobs', sa.Column('progress_percentage', sa.Float(), nullable=False))
    op.add_column('research_jobs', sa.Column('execution_time_ms', sa.Integer(), nullable=True))
    op.alter_column('research_jobs', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('research_jobs', 'depth',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.add_column('research_reports', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('research_reports', sa.Column('is_latest', sa.Boolean(), nullable=False))
    op.add_column('research_reports', sa.Column('parent_version_id', sa.Uuid(), nullable=True))
    op.alter_column('research_reports', 'word_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint('research_reports_job_id_key', 'research_reports', type_='unique')
    op.drop_index('ix_research_reports_job_id', table_name='research_reports')
    op.create_index(op.f('ix_research_reports_job_id'), 'research_reports', ['job_id'], unique=False)
    op.create_index(op.f('ix_research_reports_is_latest'), 'research_reports', ['is_latest'], unique=False)
    op.create_index('ix_research_reports_job_latest', 'research_reports', ['job_id', 'is_latest'], unique=False)
    op.create_index('ix_research_reports_job_version', 'research_reports', ['job_id', 'version'], unique=False)
    op.create_foreign_key(None, 'research_reports', 'research_reports', ['parent_version_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('role', sa.String(length=20), nullable=False))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint('uq_users_google_sub', 'users', type_='unique')
    op.drop_index('ix_users_google_sub', table_name='users')
    op.create_index(op.f('ix_users_google_sub'), 'users', ['google_sub'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration.

    This function is executed by ``alembic downgrade``.

    IMPORTANT: Always verify that downgrade() correctly undoes
    upgrade() — data loss is possible for DROP TABLE / DROP COLUMN.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_google_sub'), table_name='users')
    op.create_index('ix_users_google_sub', 'users', ['google_sub'], unique=False)
    op.create_unique_constraint('uq_users_google_sub', 'users', ['google_sub'])
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.drop_column('users', 'role')
    op.drop_constraint(None, 'research_reports', type_='foreignkey')
    op.drop_index('ix_research_reports_job_version', table_name='research_reports')
    op.drop_index('ix_research_reports_job_latest', table_name='research_reports')
    op.drop_index(op.f('ix_research_reports_is_latest'), table_name='research_reports')
    op.drop_index(op.f('ix_research_reports_job_id'), table_name='research_reports')
    op.create_index('ix_research_reports_job_id', 'research_reports', ['job_id'], unique=True)
    op.create_unique_constraint('research_reports_job_id_key', 'research_reports', ['job_id'])
    op.alter_column('research_reports', 'word_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_column('research_reports', 'parent_version_id')
    op.drop_column('research_reports', 'is_latest')
    op.drop_column('research_reports', 'version')
    op.alter_column('research_jobs', 'depth',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'standard'::character varying"),
               existing_nullable=False)
    op.alter_column('research_jobs', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=False)
    op.drop_column('research_jobs', 'execution_time_ms')
    op.drop_column('research_jobs', 'progress_percentage')
    op.drop_column('research_jobs', 'current_agent')
    op.alter_column('payments', 'credits_awarded',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('payments', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=False)
    op.alter_column('payments', 'currency',
               existing_type=sa.VARCHAR(length=3),
               server_default=sa.text("'usd'::character varying"),
               existing_nullable=False)
    op.drop_column('payments', 'error_message')
    op.drop_column('payments', 'retry_count')
    op.drop_column('payments', 'cost_usd')
    op.alter_column('agent_execution_logs', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'running'::character varying"),
               existing_nullable=False)
    op.drop_column('agent_execution_logs', 'cost_usd')
    # ### end Alembic commands ###
