// orchestrator/types.ts
// Shared TypeScript types for the Multi-Step Research Agent pipeline.

export type PipelineStepStatus = 'pending' | 'running' | 'done' | 'error';

/** Represents one step in the 5-stage research pipeline. */
export interface PipelineStep {
  id: string;
  name: string;
  description: string;
  api: string;
  status: PipelineStepStatus;
  cost?: string;       // e.g. "0.0025 USDC"
  duration?: number;   // ms elapsed since pipeline start
  error?: string;
}

/**
 * A payment receipt generated by the x402 payment layer for each paid API call.
 *
 * Network variants:
 *   - 'Algorand Testnet (Simulation)' — no mnemonic set, full protocol demo
 *   - 'Algorand Testnet'              — real on-chain USDC ASA 10458941 transfer
 *
 * In simulation mode the txHash is a randomly generated 52-char base32 string
 * matching Algorand's transaction ID format.
 */
export interface PaymentReceipt {
  stepId: string;
  stepName: string;
  amount: string;      // e.g. "0.0025"
  currency: 'USDC';
  network: 'Algorand Testnet (Simulation)' | 'Algorand Testnet';
  txHash: string;      // 52-char base32 Algorand Transaction ID
  explorerUrl: string; // Lora Explorer URL: https://lora.algokit.io/testnet/transaction/{txId}
  from: string;        // agent wallet address (Algorand public address)
  payTo: string;       // API provider / receiver wallet address
  assetId: number;     // USDC Testnet ASA ID (10458941)
  timestamp: string;   // ISO 8601
}

/** Server-Sent Event payload streamed to the frontend during pipeline execution. */
export type PipelineEventType =
  | 'ping'
  | 'step_start'
  | 'step_done'
  | 'step_error'
  | 'payment'
  | 'complete'
  | 'pipeline_error';

export interface PipelineEvent {
  type: PipelineEventType;
  sessionId: string;
  timestamp: string;
  step?: PipelineStep;
  payment?: PaymentReceipt;
  error?: string;
  totalCost?: string;
}

// ─── Intermediate pipeline data ───────────────────────────────────────────────

export interface DecomposeResult {
  subQuestions: string[];
  researchDomain: string;
  mainThesis: string;
}

export interface SearchResult {
  query: string;
  text: string;
}

export interface FactCheckResult {
  verifiedClaims: string[];
  keyEntities: string[];
  confidence: number;
}

export interface EnrichmentResult {
  entity: string;
  summary: string;
  url: string;
}

// ─── Final pipeline output ────────────────────────────────────────────────────

export interface ResearchSource {
  index: number;
  title: string;
  authors: string;
  year: number;
  journal: string;
  relevance: number;
  doi: string;
  url: string;
  tags: string[];
  abstract: string;
}

export interface ResearchSection {
  heading: string;
  body: string;
  bulletPoints?: string[];
}

export interface ResearchPipelineResult {
  title: string;
  overview: string;
  sections: ResearchSection[];
  codeSnippet: string;
  sources: ResearchSource[];
  pipelineSteps: PipelineStep[];
  payments: PaymentReceipt[];
  totalCost: string;
}
