from datetime import datetime, timezone
from typing import List
from pydantic import BaseModel, Field


class ResearchTask(BaseModel):
    """
    Represents an individual subtask generated by the Planner Agent.
    """
    task_id: str = Field(..., description="Unique identifier for the subtask (e.g., 'task-1')")
    description: str = Field(..., description="Detailed description of the research goal for this task")
    expected_output: str = Field(..., description="Description of expected outcome or artifact from this task")
    estimated_services: List[str] = Field(
        default_factory=list,
        description="Services/APIs estimated to be required (e.g., ['search', 'fact_check'])"
    )
    dependencies: List[str] = Field(
        default_factory=list,
        description="List of task_ids that must be completed prior to executing this task"
    )
    priority: int = Field(default=1, description="Priority rank for execution scheduling (lower numbers = higher priority)")


class ExecutionPlan(BaseModel):
    """
    Represents the full execution plan composed of multiple subtasks ordered into parallel stages.
    """
    plan_id: str = Field(..., description="Unique identifier for the execution plan")
    query: str = Field(..., description="Original user research query")
    tasks: List[ResearchTask] = Field(..., description="All subtasks required to fulfill the research query")
    execution_order: List[List[str]] = Field(
        ...,
        description="Subtasks grouped into sequential execution stages where tasks within each stage run in parallel"
    )
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Timestamp when the plan was created"
    )


class PlanDecompositionSchema(BaseModel):
    """
    Structured output schema for LLM query decomposition calls.
    """
    tasks: List[ResearchTask] = Field(..., description="Ordered list of research tasks with valid dependencies")

